fix(formSync): add IE11 support
joinbox/ui-components pull request #28
Opened 2021-05-04 09:30 UTC by fxstr

2021-05-04 12:22 UTC, andimeier-ch requested changes

2021-05-04 12:22 UTC, andimeier-ch commented on FormSync/FormSync.js
> +            const clone = template.content.cloneNode(true).firstElementChild;
Das Problem ist mit `template.content`, nicht mit `firstElementChild` oder `cloneNode()`. Das wird auch nicht funktionieren auf IE11.

2021-05-04 14:15 UTC, fxstr commented on FormSync/FormSync.js
> +            const clone = template.content.cloneNode(true).firstElementChild;
🙈  My Bad! Ich hab bei deinem Code tatsächlich das fehlende `content`-Segment übersehen. Schade, das wäre ein easy Fix gewesen. Update kommt. Sorry.

2021-05-05 04:57 UTC, andimeier-ch approved these changes
Hab den Code getestet im IE11 👍

2021-05-05 06:18 UTC, merged